image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install && cd src-tauri && cargo build --no-default-features
    command: "yarn tauri dev"

ports:
  - name: VNC UI
    port: 6080
    onOpen: open-browser

github:
  prebuilds:
    addCheck: true
